version: '3.8'
services:
  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    volumes:
      - ./extra_addons:/mnt/extra_addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo_19-odoo-data:/var/lib/odoo
      # - odoo_19-odoo-logs:/var/log/odoo
    environment:
      - HOST=${ODOO_DB_HOST}
      - USER=${ODOO_DB_USER}
      - PASSWORD=${ODOO_DB_PASSWORD}
      - ADMIN_PASSWD=${ODOO_MASTER_PASSWORD}
    command: odoo -c /etc/odoo/odoo.conf
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - odoo_19-db-data:/var/lib/postgresql/data
volumes:
  odoo_19-odoo-data:
  odoo_19-db-data:
  odoo_19-odoo-logs: